package tests;// Generated by Selenium IDE

import model.ContactData;
import model.GroupData;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import ru.stqa.addressbook.common.CommonFunctions;

import java.util.ArrayList;
import java.util.Random;

public class ContactRemovalTests extends TestBase {

    @Test
    public void CanRemoveContact() {
        if (app.contacts().getCount() == 0) {
            app.contacts().createContact(new ContactData("", "lastname", "firstname", "middlename", "", "", "", "", "", ""));

        }
        var oldContacts = app.hbm().getContactList();
        var rnd = new Random();
        var index = rnd.nextInt(oldContacts.size());
        app.contacts().RemoveContact(oldContacts.get(index));
        var newContacts = app.hbm().getContactList();
        var expectedList = new ArrayList<>(oldContacts);
        expectedList.remove(index);
        Assertions.assertEquals(newContacts, expectedList);
    }

    @Test
    void canDeleteContactFromGroup() {
        var groups = app.hbm().getGroupList();
        if (groups.size()==0) {
            app.hbm().createGroup(new GroupData("", CommonFunctions.randomString(10), CommonFunctions.randomString(10), CommonFunctions.randomString(10)));
            groups = app.hbm().getGroupList();
        }
        var group = groups.get(0);
        if (app.hbm().getContactInGroup(group).isEmpty()) {
            var contact = new ContactData()
                    .withFirstname(CommonFunctions.randomString(10))
                    .withLastname(CommonFunctions.randomString(10))
                    .withPhoto(randomFile("src/test/resources/images"));
            app.contacts().createContact(contact);
            contact = app.hbm().getContactList().get(0);
            app.contacts().addContactInGroup(contact, group);
        }
        var oldRelated = app.hbm().getContactInGroup(group);
        var contactToRemove = oldRelated.get(0);
        app.contacts().deleteContactFromGroup(contactToRemove, group);
        var newRelated = app.hbm().getContactInGroup(group);
        Assertions.assertEquals(oldRelated.size() - 1, newRelated.size());
    }
}

