package tests;// Generated by Selenium IDE

import model.ContactData;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.MethodSource;
import ru.stqa.addressbook.common.CommonFunctions;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;

public class ContactCreationTests extends TestBase {

    @Test
    public void CanCreateContact() {
        var contact = new ContactData()
                .withFirstname(CommonFunctions.randomString(10))
                .withLastname(CommonFunctions.randomString(10))
                .withPhoto(randomFile("src/test/resources/images"));
        app.contacts().createContact(contact);
    }


    public static List<ContactData> contactProvider() {
        var result = new ArrayList<ContactData>();
        for (var lastname : List.of("lastname","")) {
            for (var firstname : List.of("firstname","")) {
                for (var middlename : List.of("middlename", "")) {
                    result.add(new ContactData().withLastname(lastname).withFirstname(firstname).withMiddlename(middlename));
                }
            }
        }
        for (int i = 0; i < 5; i++) {
            result.add(new ContactData()
                    .withLastname(CommonFunctions.randomString(i * 10))
                    .withFirstname(CommonFunctions.randomString(i * 10))
                    .withMiddlename(CommonFunctions.randomString(i * 10)));
        }
        return result;
    }

    @ParameterizedTest
    @MethodSource("contactProvider")
    public void canCreateMultipleContacts(ContactData contact) {
        var oldContacts = app.contacts().getList();
        app.contacts().createContact(contact);
        var newContants = app.contacts().getList();
        Comparator<ContactData> compareById = (o1, o2) -> {
            return Integer.compare(Integer.parseInt(o1.id()), Integer.parseInt(o2.id()));
        };
        newContants.sort(compareById);
        var expectedList = new ArrayList<>(oldContacts);
        expectedList.add(contact.withId(newContants.get(newContants.size() - 1).id()).withMiddlename(""));
        expectedList.sort(compareById);
        Assertions.assertEquals(newContants, expectedList);
    }
}
