package tests;// Generated by Selenium IDE

import model.ContactData;
import org.junit.jupiter.api.Test;

public class ContactRemovalTests extends TestBase {

    @Test
    public void CanRemoveContact() {

        if (!app.contacts().isContactPresent()) {
            app.contacts().createContact(new ContactData("firstname", "middlename", "lastname"));

        }
        app.contacts().RemoveContact();
    }

}
