package tests;// Generated by Selenium IDE

import model.ContactData;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import ru.stqa.addressbook.common.CommonFunctions;

import java.util.ArrayList;
import java.util.Random;

public class ContactRemovalTests extends TestBase {

    @Test
    public void CanRemoveContact() {
        if (app.contacts().getCount() == 0) {
            app.contacts().createContact(new ContactData("", "lastname", "firstname", "middlename", "", ""));

        }
        var oldContacts = app.hbm().getContactList();
        var rnd = new Random();
        var index = rnd.nextInt(oldContacts.size());
        app.contacts().RemoveContact(oldContacts.get(index));
        var newContacts = app.hbm().getContactList();
        var expectedList = new ArrayList<>(oldContacts);
        expectedList.remove(index);
        Assertions.assertEquals(newContacts, expectedList);
    }

    @Test
    public void canDeleteContactFromGroup() {
        var contacts = app.hbm().getContactList();
        var groups = app.hbm().getGroupList();

        outerLoop:
        for (int i = 0; i < groups.size(); i++) {
            for (int j = 0; j < contacts.size(); j++) {
                var oldRelated = app.hbm().getContactInGroup(groups.get(i));
                if (oldRelated.size() == 0) {
                    var contact = new ContactData()
                            .withFirstname(CommonFunctions.randomString(10))
                            .withLastname(CommonFunctions.randomString(10))
                            .withPhoto(randomFile("src/test/resources/images"));
                    app.contacts().createContact(contact);
                    app.contacts().addContactInGroup(contacts.get(j), groups.get(i));
                }
                oldRelated = app.hbm().getContactInGroup(groups.get(i));
                app.contacts().deleteContactFromGroup(contacts.get(j), groups.get(i));
                var newRelated = app.hbm().getContactInGroup(groups.get(j));
                if (oldRelated.size() - 1 == newRelated.size()) {
                    Assertions.assertEquals(oldRelated.size() - 1, newRelated.size());
                    break outerLoop;
                }
            }
        }
    }
}
