package tests;// Generated by Selenium IDE

import model.ContactData;
import model.GroupData;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.MethodSource;

import java.util.ArrayList;
import java.util.List;

public class ContactCreationTests extends TestBase {

  @Test
  public void CanCreateContact() {
    app.contacts().createContact(new ContactData("firstname", "middlename", "lastname"));
  }


  public static List<ContactData> contactProvider() {
    var result = new ArrayList<ContactData>();
    for (var firstname: List.of("firstname","")) {
      for (var middlename: List.of("middlename","")) {
        for (var lastname: List.of("lastname","")) {
          result.add(new ContactData(firstname,middlename,lastname));
        }
      }
    }
    for (int i = 0; i < 5; i++) {
      result.add(new ContactData(randomString(i * 10), (randomString(i * 10)), (randomString(i * 10))));
    }
    return result;
  }

  @ParameterizedTest
  @MethodSource("contactProvider")
  public void canCreateMultipleContacts(ContactData contact) {
    int contactsCount = app.contacts().getCount();
    app.contacts().createContact(contact);
    int newContactsCount = app.contacts().getCount();
    Assertions.assertEquals(contactsCount + 1, newContactsCount);
  }
}
